name: push-schema-to-dev

on:
  push:
    branches: [dev]
    paths: ['src/api/drizzle/schema.ts']

jobs:
  deploy-migrations-to-dev:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.0]
        pnpm-version: [7.29.3]

    steps:
      - name: Print event
        run: echo ${{ github.event_name }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file
        run: echo PLANETSCALE_CONNECTION_URL=${{ secrets.PSCALE_DEV_DATABASE_URL }}?ssl={"rejectUnauthorized":true} > .env

      - uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
          run: yarn install

      - run: yarn add -D drizzle-kit
      - run: yarn add drizzle-kit
      - name: Push schema changes
        run: yarn push
